version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: simplereact

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - export COMMIT_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Setting image tag
      - export IMAGE_TAG=`date +%y.%m%d`.$CODEBUILD_BUILD_NUMBER.$COMMIT_TAG
  build:
    commands:
      - echo Building the Docker image with tag $IMAGE_TAG
      - docker build -f Dockerfile.build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo Writing image definitions file...
      - printf '[{"name":"SampleApp-FargateTaskContainer-simplereact","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
